source 'git@git.pixio.com:pixio-libraries/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'UIAlertController-BetterConstructor', :exclusive => true do
  pod "UIAlertController-BetterConstructor", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "UIAlertController-BetterConstructor", :path => "../"

  
end
