source 'https://github.com/CocoaPods/Specs.git'

target 'UIAlertController-BetterConstructor' do
  pod "UIAlertController-BetterConstructor", :path => "../"
end

target 'Tests' do
  pod "UIAlertController-BetterConstructor", :path => "../"
end
